/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface LimecComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLLimecComponentElement extends StencilComponents.LimecComponent, HTMLStencilElement {}

  var HTMLLimecComponentElement: {
    prototype: HTMLLimecComponentElement;
    new (): HTMLLimecComponentElement;
  };
  interface HTMLElementTagNameMap {
    'limec-component': HTMLLimecComponentElement;
  }
  interface ElementTagNameMap {
    'limec-component': HTMLLimecComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'limec-component': JSXElements.LimecComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface LimecComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;